//File:		MainDialog.java
//Author:	Gary Bezet
//Date:		2016-07-14
//Desc:		This program was created to help Nick download videos from the Louisiana House or Representatives video on demand site at 
//HORWebsite:   http://house.louisiana.gov/H_Video/Hse_Video_OnDemand.aspx


package net.garyscorner.lahordownloader;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;




public class MainDialog extends javax.swing.JDialog {
    
    //my variables
    JFileChooser filechooser;
    FileNameExtensionFilter filter;
    
    
    //my functions
    
    //initialize my stuff
    public void myinit() {
        filechooser = new JFileChooser();
        filter = new FileNameExtensionFilter("MP4 Video", "mp4");
        filechooser.setFileFilter(filter);
        
    }
    
    //validate the URL
    private URL validateURL(String url) {
        
        
        URL returnvalue;
        try {
            returnvalue = new URL(url);
        } catch (MalformedURLException ex) {
            System.err.printf("Bad URL provided:  %1$s", url);
            JOptionPane.showMessageDialog(this, "Bad URL!", "Error", JOptionPane.ERROR_MESSAGE);
            returnvalue = null;
        }
        
        return returnvalue;
    }
    
    
    
    //setup the download process
    private void startdownload(URL url, String savefile)  {
        JOptionPane.showMessageDialog(null, "SaveFile:  " + savefile);
        
                
        DownloadDialog downloaddialog = new DownloadDialog(null, false);
        downloaddialog.myinit(url, savefile);
        
        downloaddialog.setVisible(true);
        
    }
    
    /**
     * Creates new form MainDialog
     */
    public MainDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textfield_url = new javax.swing.JTextField();
        jButton_download = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItem_About = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton_download.setText("Download");
        jButton_download.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_downloadActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        MenuBar.add(jMenu1);

        MenuItem_About.setText("About");
        MenuBar.add(MenuItem_About);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textfield_url)
            .addComponent(jButton_download, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(textfield_url, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_download))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_downloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_downloadActionPerformed
        
        System.err.println("Validating the URL...");
        URL url = this.validateURL(this.textfield_url.getText());
        if(url != null) {

            System.err.println("Download clicked open save dialog...");

            //if they approved file then go for the download
            if( filechooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION ) {
                this.startdownload( url, filechooser.getSelectedFile().getName() );
            }
        }
        
        
    }//GEN-LAST:event_jButton_downloadActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MenuItem_About;
    private javax.swing.JButton jButton_download;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTextField textfield_url;
    // End of variables declaration//GEN-END:variables
}
